# Generated by Django 3.2.8 on 2021-10-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'Genres'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='genre',
        ),
    ]
